services:
  - type: web
    name: apk-analyzer
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 2 --bind 0.0.0.0:$PORT --limit-request-line 0 --limit-request-field_size 0
    plan: free
    autoDeploy: true
